services:
  app:
    build:
      context: bloglist-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./bloglist-frontend/:/usr/src/app
    container_name: bloglist-frontend-dev

  server:
    build:
      context: bloglist-backend
      dockerfile: dev.Dockerfile
    env_file:
      - ./bloglist-backend/.env
    volumes:
      - ./bloglist-backend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: bloglist-backend-dev

  reverse-proxy:
    image: nginx:1.31.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
    container_name: bloglist-nginx-dev

  mongo:
    image: mongo:8.3.4-noble
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./bloglist-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-backend-mongo

volumes:
  mongo_data:
